name: Greetings
on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Send greeting for issues
        if: github.event_name == 'issues'
        run: |
          echo "::set-output name=message::👋 Thank you @${{ github.actor }} for raising an issue! We appreciate your effort in helping us improve. Our team will review it shortly. Stay tuned!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send greeting for pull requests
        if: github.event_name == 'pull_request_target'
        run: |
          echo "::set-output name=message:: 🎉 Thank you @${{ github.actor }} for your contribution! Your pull request has been submitted successfully. A maintainer will review it as soon as possible. We appreciate your support in making this project better."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
